job_data = {
    "title": "First test job",
    "industry": "Test ",
    "category": "Test ",
    "summary": "Test ",
    "salary_min": 10000,
    "salary_max": 50000,
    "product_type": 1,
    "valid_duration": 30,
    "company": "Test Company",
    "country": "Australia",
    "state": "QLD",
    "city": "Brisbane",
    "employment_type": "Test ",
    "remote_status": "Test ",
    "salary_currency": "$",
    "content": "Test ",
    "contact_name": "Test name",
    "contact_number": "0491020584",
    "perk_car": True,
    "perk_visa": False,
    "perk_relocation": False,
    "perk_days_week": 5,
    "perk_phone": False,
    "perk_laptop": False,
    "perk_bonus": False
}

jobs_data = [{
    "title": "First test job",
    "industry": "Test ",
    "category": "Test ",
    "summary": "Test ",
    "salary_min": 10000,
    "salary_max": 50000,
    "product_type": 1,
    "valid_duration": 30,
    "company": "Test Company",
    "country": "Australia",
    "state": "QLD",
    "city": "Brisbane",
    "employment_type": "Test ",
    "remote_status": "Test ",
    "salary_currency": "$",
    "content": "Test ",
    "contact_name": "Test name",
    "contact_number": "0491020584",
    "perk_car": True,
    "perk_visa": False,
    "perk_relocation": False,
    "perk_days_week": 5,
    "perk_phone": False,
    "perk_laptop": False,
    "perk_bonus": False
}, {
    "title": "Second test job",
    "industry": "Test ",
    "category": "Test ",
    "summary": "Test ",
    "salary_min": 10000,
    "salary_max": 50000,
    "product_type": 1,
    "valid_duration": 30,
    "company": "Test Company",
    "country": "Australia",
    "state": "QLD",
    "city": "Brisbane",
    "employment_type": "Test ",
    "remote_status": "Test ",
    "salary_currency": "$",
    "content": "Test ",
    "contact_name": "Test name",
    "contact_number": "0491020584",
    "perk_car": True,
    "perk_visa": False,
    "perk_relocation": False,
    "perk_days_week": 5,
    "perk_phone": False,
    "perk_laptop": False,
    "perk_bonus": False
}]

job_application = {
    "recruiter_status": "active",
    "job_id": 1,
    "cv_id": 1,
    "cover_letter_id": 1
}

